# Generated by Django 5.1.1 on 2025-05-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dds.cashflowsubcategory'),
            preserve_default=False,
        ),
    ]
