# Generated by Django 5.1.1 on 2025-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_cashflow_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowcategory',
            name='verbose_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
