# Generated by Django 5.1.1 on 2025-05-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_cashflowcategory_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowsubcategory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dds.cashflowtype'),
            preserve_default=False,
        ),
    ]
