# Generated by Django 5.1.1 on 2025-05-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_cashflowsubcategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowsubcategory',
            name='type',
        ),
        migrations.AddField(
            model_name='cashflowcategory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dds.cashflowtype'),
            preserve_default=False,
        ),
    ]
