# Generated by Django 5.1.1 on 2025-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0005_remove_cashflowsubcategory_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'verbose_name': 'Движение Денежных Средств', 'verbose_name_plural': 'Движения Денежных Средств'},
        ),
        migrations.AlterModelOptions(
            name='cashflowcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='cashflowsubcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='cashflowtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cashflowcategory',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashflowstatus',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashflowsubcategory',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashflowtype',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
